#Test each function in pseudo_seq.R
context("Update_gap.R script testing process start:")

#testing material

s1 = "AAT---AAACAAAGAATGCTTACTGT---ATAAGGCTTACTGTTCTAGCG---ATCACCGCG---TCATGTCTAGTTATGAACGGC------GGTTTAACATTGAATAGCAAGGCACTTCCATAATAGGGCCGTC---GTAATTGTCTGAATATAG------ATA------"
s2 = "------AAGTAG---AATTTGATGCTACATTGGATGAGTCTACTTCGAGCGCGCCGCATCGATTGCAAGAGCAGTGTTGCCT---AAGAGCCGTTAGATGCGTCGTTG---ATCGCGTCCGATAATTCGGGAGTTG---CCCAATATTTAATATGATGA---TAG---TAA"


m = "AAT---AAACAAAGAATGCTTACTGT---ATAAGGCTTACTGTTCTAGCG---ATCACCGCG---TCATGTCTAGTTATGAACGGC------GGTTTAACATTGAATAGCAAGGCACTTCCATAATAGGGCCGTC---GTAATTGTCTAATATAG------ATAGTA---"
r = "TAA------AA---AATTTGATGCTACATTGGATGAGTCTACTTCGAGCGCGCCGCATCGATTGCAAGAGCAGTGTTGCCT---AAGAGCCGTTAGATGCGTCGTTG---ATCGCGTCCGATAATTCGGGAGTTG---CCCAATATTTAATATGATGA---TAGCTATAA"

m.1 = "AATTACAAACAAAGAATGCTTACTGTATGCATAAGGCTTACTGTTCTAGCGGAGATCACCGCGTCATGTCTAGTTATGAACGGCGGTTTAACATTGAATAGCAAGGCACTTCCATAATAGGGCCGTCGCGGTAATTGTCTAATATAGATTTGGAATAGTATAG"
r.1 = "TAATACTGACAAAATTTGATGCTACATTGGATGAGTCTACTTCGAGCGCGCCGCATCGATTGCAAGAGCAGTGTTGGAAGAGCCGTTAGATGCGTCGTTGTGAATCGCGTCCGATAATTCGGGAGTTGCGCCCCAATATTTAATATGATGATTATAGCTATAA"

m.2 = "AAT---AAACAAAGAATGCTTACTGT---ATAAGGCTTACTGTTCTAGCG---ATCACCGCG---TCATGTCTAGTTATGAACGGC------GGTTTAACATTGAATAGCAAGGCACTTCCATAATAGGGCCGTC---GTAATTGTCTAATATAG------ATAGTA---"
r.2 = "------TGACAAAATTTGATGCTACATTGGATGAGTCTACTTCGAGCGCGCCGCATCGATTGCAAGAGCAGTGTTGGAAGAGCCGTTAGATGCGTCGTTGTGAATCGCGTCCGATAATTCGGGAGTTGCGCCCCAATATTTAATATGATGATTATAGCTATAAAGTAGAT"


###############################################################################
#Predicted Results

S1 = "AAT===AAACAAAGAATGCTTACTGT---ATAAGGCTTACTGTTCTAGCG---ATCACCGCG---TCATGTCTAGTTATGAACGGC------GGTTTAACATTGAATAGCAAGGCACTTCCATAATAGGGCCGTC---GTAATTGTCTGAATATAG------ATA======"
S2 = "======AAGTAG---AATTTGATGCTACATTGGATGAGTCTACTTCGAGCGCGCCGCATCGATTGCAAGAGCAGTGTTGCCT---AAGAGCCGTTAGATGCGTCGTTG---ATCGCGTCCGATAATTCGGGAGTTG---CCCAATATTTAATATGATGA---TAG===TAA"

#Here "TAA======AA" is due to two events : remove start gaps and normal adjacent gaps.
M = "AAT===AAACAAAGAATGCTTACTGT---ATAAGGCTTACTGTTCTAGCG===ATCACCGCG===TCATGTCTAGTTATGAACGGC------GGTTTAACATTGAATAGCAAGGCACTTCCATAATAGGGCCGTC===GTAATTGTCTAATATAG------ATAGTA==="
R = "TAA======AA===AATTTGATGCTACATTGGATGAGTCTACTTCGAGCGCGCCGCATCGATTGCAAGAGCAGTGTTGCCT===AAGAGCCGTTAGATGCGTCGTTG---ATCGCGTCCGATAATTCGGGAGTTG===CCCAATATTTAATATGATGA===TAGCTATAA"


M.1 = "AATTACAAACAAAGAATGCTTACTGTATGCATAAGGCTTACTGTTCTAGCGGAGATCACCGCGTCATGTCTAGTTATGAACGGCGGTTTAACATTGAATAGCAAGGCACTTCCATAATAGGGCCGTCGCGGTAATTGTCTAATATAGATTTGGAATAGTATAG"
R.1 = "TAATACTGACAAAATTTGATGCTACATTGGATGAGTCTACTTCGAGCGCGCCGCATCGATTGCAAGAGCAGTGTTGGAAGAGCCGTTAGATGCGTCGTTGTGAATCGCGTCCGATAATTCGGGAGTTGCGCCCCAATATTTAATATGATGATTATAGCTATAA"

M.2 = "AAT===AAACAAAGAATGCTTACTGT---ATAAGGCTTACTGTTCTAGCG===ATCACCGCG===TCATGTCTAGTTATGAACGGC------GGTTTAACATTGAATAGCAAGGCACTTCCATAATAGGGCCGTC---GTAATTGTCTAATATAG------ATAGTA==="
R.2 = "======TGACAAAATTTGATGCTACATTGGATGAGTCTACTTCGAGCGCGCCGCATCGATTGCAAGAGCAGTGTTGGAAGAGCCGTTAGATGCGTCGTTGTGAATCGCGTCCGATAATTCGGGAGTTGCGCCCCAATATTTAATATGATGATTATAGCTATAAAGTAGAT"


# Test Index func.
test_that("Test Update_() ",{
  expect_equal(start_stop_test(s1),S1)
  expect_equal(start_stop_test(s2),S2)
  expect_equal(Update_(m,r),c(M,R) )
  expect_equal(Update_(m.1,r.1),c(M.1,R.1) )
  expect_equal(Update_(m.2,r.2),c(M.2,R.2) )
})
